# $LOCAL_DIR/share -> git repos / source code
# $LOCAL_DIR/etc   -> dotfiles
# $LOCAL_DIR/bin   -> executables
LOCAL_DIR="${HOME}/Dev/dotfiles"; export LOCAL_DIR
PATH="${LOCAL_DIR}/bin:${PATH}"
EDITOR="vim"

HISTFILE="${HOME}/.zsh_history"
HISTSIZE=1000
SAVEHIST=1000
setopt autocd notify
unsetopt beep

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' max-errors 3
zstyle :compinstall filename "${HOME}/.zshrc"
autoload -Uz compinit && compinit
# End of lines added by compinstall

ASDF_DIR="${LOCAL_DIR}/share/asdf"; export ASDF_DIR
ASDF_DATA_DIR="${ASDF_DIR}"; export ASDF_DATA_DIR
if [[ -d "${ASDF_DIR}" ]]; then
  source "${ASDF_DIR}/asdf.sh"
  fpath=("${ASDF_DIR}/completions" $fpath)
fi

HOMEBREW_DIR="${LOCAL_DIR}/share/homebrew"; export HOMEBREW_DIR
if [[ -d "${HOMEBREW_DIR}" ]]; then
  eval "$($HOMEBREW_DIR/bin/brew shellenv)"
  fpath=("${HOMEBREW_DIR}/share/zsh/site-functions" $fpath)
fi

alias rm='rm -i'
alias mkdir='mkdir -p'
alias ll='ls -alh'
alias l='ls -l'
alias d='docker $*'
alias c='docker-compose $*'
alias v='${EDITOR} $*'
alias g='git'

PS1="%~
%# "

